//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuMarket_App.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IlyasovaEntities : DbContext
    {
        private static IlyasovaEntities _context;
        public IlyasovaEntities()
            : base("name=IlyasovaEntities")
        {
        }

        public static IlyasovaEntities GetContext()
        {
            if (_context == null)
                _context = new IlyasovaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallingWizard> CallingWizard { get; set; }
        public virtual DbSet<JobType> JobType { get; set; }
        public virtual DbSet<MeterReadings> MeterReadings { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
