//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuMarket_App.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public string Adress { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ServiseId { get; set; }
        public Nullable<long> Number { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual User User { get; set; }

        public Payment() { }
        public Payment(string adress, long? number, Services services, User user)
        {
            this.Adress = adress;
            this.Number = number;
            this.Services = services;
            this.User = user;
        }
    }
}
